Remove Timed Control Tasks
Alpha-CubeSat/oop-flight-code pull request #144
Opened 2023-10-11 14:41 UTC by ljgreenhill

# Remove Timed Control Tasks

- Added retries if RockBLOCK serial sequence fails
- Remove clock manager and handle short cycles in main control loop
- Remove timed control task logic

2023-10-11 15:32 UTC, ewz4 approved these changes
Looks good!

2023-10-12 00:23 UTC, Duncan-McD requested changes
I think we should keep timing stuff out of main control loop in clock manager. We can still remove timed control tasks

Otherwise it all looks good

2023-10-12 00:23 UTC, Duncan-McD commented on src/ClockManager.cpp
> -    sfr::mission::cycle_dur = constants::timecontrol::control_cycle_time - cycle_dt;
We should continue to track these three values in main control loop - personally I like having this stuff sill in clock manager, we could leave clock manager while still remove timed control tasks

2023-10-12 14:05 UTC, Duncan-McD approved these changes
Looks good!

2023-10-12 14:22 UTC, merged