Fragment Requests
Alpha-CubeSat/oop-flight-code pull request #150
Opened 2023-10-26 05:49 UTC by ewz4

# Fragment Requests

### Summary of changes
Added support for camera and IMU report fragment requests.

### Testing

### SFR Changes
None

2023-11-30 20:39 UTC, dhacks541 commented
Latest version of the camera and IMU downlink functionality has been successfully tested in simulated deployment scenario, requesting review for merge.

2023-11-30 21:52 UTC, Duncan-McD requested changes
Agreed, looks great aside from rockblock command factory issue

2023-12-01 01:01 UTC, jonathanjma commented on src/Control Tasks/RockblockControlTask.cpp
> -        return new SFROverrideCommand(raw);
fixed

2023-12-01 01:19 UTC, dhacks541 commented
> Looks good other than that one comment. Also, wanted to confirm all of these changes have been tested with GS in the loop (for example, requesting an IMU fragment from the GS).

And yeah tested with the GS

2023-12-01 01:44 UTC, ljgreenhill approved these changes

2023-12-01 15:47 UTC, merged