Refactor sfr lauren
Alpha-CubeSat/oop-flight-code pull request #76
Opened 2022-07-19 01:56 UTC by ljgreenhill

2022-07-19 13:22 UTC, asmith22 commented on src/SFRField.hpp
> +        if (bounded && input <= max && input >= min) {
This clause is partially inverted. We want to set if its is not bounded or if it is bounded and within the range
if(!bounded || 
```suggestion
        if (bounded && input <= max && input >= min) {
```

2022-07-19 13:26 UTC, asmith22 commented on src/sfr.hpp
> +        // SFRField<float> max_time(1.0f, 0.0f, 2.0f, 1001);
Normally would req removing commented code but its mine so I'll remove it in the next PR

2022-07-19 13:28 UTC, asmith22 requested changes
Single line fix plus questions

2022-07-20 02:27 UTC, ljgreenhill commented on test/test_command_monitor/test_command_monitor.cpp
>      sfr::rockblock::waiting_command = true;
Are you saying just check if the length of the queue has changed?

2022-07-20 02:41 UTC, ljgreenhill commented on test/test_command_monitor/test_command_monitor.cpp
>      sfr::rockblock::waiting_command = true;
Merging for now- I think this is a separate issue that could be addressed later

2022-07-20 02:42 UTC, merged