Sensor value
Alpha-CubeSat/oop-flight-code pull request #82
Opened 2022-09-13 01:03 UTC by ljgreenhill

Modifying SFR to include SFRFields.

2022-09-16 02:08 UTC, Duncan-McD requested changes
Lots of little things (mostly either me requesting clarification on things or opening discussions about whether stuff should be on a different ticket or linking tickets)

Otherwise looks good - Also we should probably have a second person go through it because I very well could have overlooked something (its a lot of files)

2022-09-16 02:08 UTC, Duncan-McD commented on src/sfr.hpp
> -        // extern bool check_camera_on_failed;
We should delete these if we decide to delete the fault monitor in this pr

2022-09-16 02:09 UTC, Duncan-McD commented on src/Monitors/PhotoresistorMonitor.cpp
> -bool PhotoresistorMonitor::check_repeated_values(std::deque<int> buffer)
oh forgot buffers are in sensors now - Is that what we are transitioning to? and if so, should we remove the buffers in rockblock tasks that I didn't remove

2022-09-16 02:26 UTC, ljgreenhill commented on src/ClockManager.cpp
>      }*/
Eventually this should be uncommented once we have added the correct start times for everything in the mcl

2022-09-16 02:27 UTC, ljgreenhill commented on src/Monitors/FaultMonitor.hpp
> -#endif
Yes, that is something we should discuss- there might be some out-of-bounds faults not handled by SensorValue. Also, the min and max values for a SensorValue might not be what we want to use to trip a fault in all cases.

2022-09-16 02:29 UTC, ljgreenhill commented on src/Monitors/CommandMonitor.cpp
> +            // } else if (command.f_opcode == get_decimal_opcode(constants::rockblock::fault_check_mag_y)) {
I will make this a TODO and link it to a Jira ticket.

2022-09-16 02:30 UTC, ljgreenhill commented on src/Control Tasks/ACSControlTask.hpp
> -    int current2PWM(float current);
All ACS code will be replaced by the work @Deemocean and @ldevenecia  have been doing. I will make this a TODO and link it to a Jira ticket.

2022-09-16 02:32 UTC, ljgreenhill commented on src/MissionMode.cpp
> +    /*
I will make this a new ticket.

2022-09-16 02:33 UTC, ljgreenhill commented on src/Monitors/ACSMonitor.cpp
> -        case acs_mode_type::off:
Will make an ACS TODO ticket.

2022-09-16 02:34 UTC, ljgreenhill commented on src/Monitors/IMUMonitor.cpp
> -}
This is now part of SensorReading itself.

2022-09-16 02:34 UTC, Duncan-McD commented on src/Monitors/IMUMonitor.cpp
> -}
disregard

2022-09-16 02:35 UTC, ljgreenhill commented on src/Monitors/NormalReportMonitor.cpp
> +    sfr::rockblock::normal_report.push_back(sfr::camera::powered);*/
Will make a ticket to create the normal report format.

2022-09-16 02:37 UTC, ljgreenhill commented on src/sfr.cpp
> -        // bool check_camera_on_failed = true;
Yes I agree these should be deleted.

2022-09-16 03:07 UTC, ljgreenhill commented on src/Control Tasks/ACSControlTask.hpp
> -    int current2PWM(float current);
Removed all ACS code. FS-156

2022-09-16 03:08 UTC, ljgreenhill commented on src/Control Tasks/BurnwireControlTask.cpp
> +    sfr::burnwire::mode = (uint16_t)burnwire_mode_type::burn;
FS-157

2022-09-16 03:09 UTC, ljgreenhill commented on src/SFRField.hpp
> +        // Convert 32bit word into Target Type #TODO Joining Two uint16s
FS-158

2022-09-16 03:12 UTC, ljgreenhill commented on src/sfr.hpp
> +        //@Josh would we need to change this?
FS-159 because maybe ?

2022-09-16 03:13 UTC, ljgreenhill commented on src/Control Tasks/RockblockControlTask.hpp
> +#endif
This should work- it is currently on main and was moved.

2022-09-16 03:21 UTC, ljgreenhill commented on src/Monitors/PhotoresistorMonitor.cpp
> -bool PhotoresistorMonitor::check_repeated_values(std::deque<int> buffer)
Moved as part of SensorReading

2022-09-16 03:26 UTC, ljgreenhill commented on src/MissionMode.cpp
> +    if (sfr::battery::voltage_average->get_value(&voltage) && voltage <= sfr::battery::min_battery) {
Not intentional. Need to check two cases- voltage reading is available and it is less than the min acceptable battery or the voltage reading is invalid

2022-09-18 21:43 UTC, Duncan-McD approved these changes
Looks good to me post changes

2022-09-18 22:22 UTC, dhacks541 approved these changes
Looks good - I think with the expanded accessibility of the sfr we should consider adding a checksum to rockblock commands (will create Jira ticket)

2022-09-18 22:59 UTC, merged