Fs 136
Alpha-CubeSat/oop-flight-code pull request #84
Opened 2022-09-18 23:27 UTC by ljgreenhill

Merge Adler's command changes. Removed FaultCheckCommand.

2022-09-18 23:48 UTC, Duncan-McD commented on src/Commands/RockblockCommand.cpp
> +    } else if (false) { // TODO After SFRField Merge
SFROverrideCommand won't run

2022-09-19 00:00 UTC, Duncan-McD requested changes

2022-09-19 00:00 UTC, Duncan-McD commented on src/constants.hpp
> +        } // namespace opcodes
Do we still want these fault commands

2022-09-25 22:52 UTC, ljgreenhill commented on src/Control Tasks/RockblockControlTask.cpp
> +                // TODO: What Goes Here @Lauren
For an invalid command, we do nothing. I will just add a print for debugging purposes.

2022-10-02 20:38 UTC, Duncan-McD approved these changes
Post changes - This looks good to me

2022-10-02 21:07 UTC, merged