FS-161
Alpha-CubeSat/oop-flight-code pull request #95
Opened 2022-11-21 00:35 UTC by dhacks541

Draft pull request for interim feedback 

To do before merging:
- Update with any revised mapping bounds (once confirmed complete, update wiki)
- Rebase off FS-167 once merged
- Update IMU Report to abstract mapping logic (move mapping_bounds to constants.cpp?)
- Test on hardware

Questions:
1. What fields am I missing that we want packed into sensor faults (27-28)?

2022-12-04 23:03 UTC, ljgreenhill requested changes

2022-12-04 23:03 UTC, ljgreenhill commented on src/Monitors/NormalReportMonitor.cpp
> +std::map<uint8_t, std::vector<int>> mapping_bounds = {
make sure to limit the max size of the vector

2022-12-04 23:03 UTC, ljgreenhill commented on src/Monitors/NormalReportMonitor.cpp
> +    return round((value - mapping_bounds[index][0]) * (255 / (mapping_bounds[index][1] - mapping_bounds[index][0])));
Is this supposed to be return round(

(value - mapping_bounds[index][0]) * 

(255 / (mapping_bounds[index][1][1] - mapping_bounds[index][1][0]))

); ?

2022-12-04 23:21 UTC, ljgreenhill commented on src/Monitors/NormalReportMonitor.hpp
> +    uint8_t serialize(int index, int value);
Actually needs to be a float is preserve decimal

2023-02-15 19:08 UTC, dhacks541 commented
Primary changes in commit d768e14. Packing and serialization of normal report verified. SensorReading debugged to fix pointer issues that were preventing updates to the sensor buffers.

2023-02-19 18:24 UTC, closed without merging